title: Jimi Osheidu # your name (or website title) here
logo: "/images/Screenshot%202023-04-09%20103356.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 I am a data analyst with a background in marketing and advertising, I possess a diverse skill set that includes proficiency in data analysis, visualisation, and dashboarding using various tools such as SQL, Python, Excel, Tableau and Power BI.   
 <br><br>
  
  <br><br>
  
  <a href="https://www.linkedin.com/in/jimiosheidu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
