title: Jimi Osheidu # your name (or website title) here
logo: "/images/Screenshot%202023-04-09%20103356.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 As a data analyst with a background in marketing and advertising, I have a wide range of skills, including knowledge of data analysis, visualisation, and reporting using tools such as SQL, Python, Excel, and Tableau.   
 <br><br>
  I have experience in data cleaning, manipulation, and visualization using various tools and software.
Moreover, my experience in spotting trends, thinking strategically, and identifying solutions through my marketing and advertising career has equipped me with a unique skillset that can help companies make informed decisions.I am passionate about transforming complex data sets into actionable insights that can drive business decisions.
  <br><br>
  
  <a href="https://www.linkedin.com/in/jimiosheidu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
